name: Regios
main: net.jzx7.regios.RegiosPlugin
version: 5.9.5
authors: [Adamki11s, johnnyzerox7]
commands:
  regios:
    aliases: [reg, r]
    description: Use /regios help <Page Number>
    usage: Use /regios help for help.